version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    env_file:
      - docker.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=freelance_db

volumes:
  postgres_data: